name: Deploy Docs
on:
  push:
    branches:
      - main
      - next
  pull_request:

env:
  CF_ACCOUNT_ID: 3bc1aa6788d40843da356b67a4f49b4b
  PAGES_PROJECT_NAME: nyxx-docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Cache Dart packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Install dependencies
        run: dart pub get

      - name: Build documentation
        run: dart run jaspr_cli:jaspr build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-jaspr
          path: build/jaspr

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-jaspr
          path: build/jaspr

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: tomjschuster/cloudflare-pages-deploy-action@v0
        with:
          account-id: "${{ env.CF_ACCOUNT_ID }}"
          project-name: "${{ env.PAGES_PROJECT_NAME }}"
          api-key: "${{ secrets.CF_GLOBAL_APIKEY }}"
          email: "${{ secrets.CF_EMAIL }}"
          preview: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy next
        if: ${{ contains(fromJson('["refs/heads/next"]'), github.ref) && github.event_name == 'push' }}
        uses: tomjschuster/cloudflare-pages-deploy-action@v0
        with:
          account-id: "${{ env.CF_ACCOUNT_ID }}"
          project-name: "${{ env.PAGES_PROJECT_NAME }}"
          api-key: "${{ secrets.CF_GLOBAL_APIKEY }}"
          email: "${{ secrets.CF_EMAIL }}"
          branch: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy production
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: tomjschuster/cloudflare-pages-deploy-action@v0
        with:
          account-id: "${{ env.CF_ACCOUNT_ID }}"
          project-name: "${{ env.PAGES_PROJECT_NAME }}"
          api-key: "${{ secrets.CF_GLOBAL_APIKEY }}"
          email: "${{ secrets.CF_EMAIL }}"
          production: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
